name: JavaScript
permissions:
  contents: read
"on":
  workflow_call:
    secrets:
      OPERATOR_PRIVATE_KEY:
        required: true
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-labs/actions/checkout@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: shikanime-labs/actions/nix/setup@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - id: direnv
        uses: shikanime-labs/actions/direnv@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
      - uses: shikanime-labs/actions/pnpm/integration@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
  build-workspace:
    name: Build (Workspace)
    runs-on: ubuntu-latest
    steps:
      - id: createGithubAppToken
        continue-on-error: true
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ vars.OPERATOR_APP_CLIENT_ID }}
          permission-contents: read
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-labs/actions/checkout@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - uses: shikanime-labs/actions/nix/setup@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token || secrets.GITHUB_TOKEN }}
      - id: direnv
        uses: shikanime-labs/actions/direnv@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
      - uses: shikanime-labs/actions/pnpm/integration@a91a9b57c78121e303aa30aea2d8ed2ee03ff45f # v9
        with:
          recursive: true
